// visibility_control.h

#ifndef DFROBOT_DC_MOTOR_HARDWARE__VISIBILITY_CONTROL_H_
#define DFROBOT_DC_MOTOR_HARDWARE__VISIBILITY_CONTROL_H_

#if defined _WIN32 || defined __CYGWIN__
#ifdef __GNUC__
#define DFROBOT_DC_MOTOR_HARDWARE_EXPORT __attribute__((dllexport))
#define DFROBOT_DC_MOTOR_HARDWARE_IMPORT __attribute__((dllimport))
#else
#define DFROBOT_DC_MOTOR_HARDWARE_EXPORT __declspec(dllexport)
#define DFROBOT_DC_MOTOR_HARDWARE_IMPORT __declspec(dllimport)
#endif
#ifdef DFROBOT_DC_MOTOR_HARDWARE_BUILDING_DLL
#define DFROBOT_DC_MOTOR_HARDWARE_PUBLIC DFROBOT_DC_MOTOR_HARDWARE_EXPORT
#else
#define DFROBOT_DC_MOTOR_HARDWARE_PUBLIC DFROBOT_DC_MOTOR_HARDWARE_IMPORT
#endif
#define DFROBOT_DC_MOTOR_HARDWARE_PUBLIC_TYPE DFROBOT_DC_MOTOR_HARDWARE_PUBLIC
#define DFROBOT_DC_MOTOR_HARDWARE_LOCAL
#else
#define DFROBOT_DC_MOTOR_HARDWARE_EXPORT __attribute__((visibility("default")))
#define DFROBOT_DC_MOTOR_HARDWARE_IMPORT
#if __GNUC__ >= 4
#define DFROBOT_DC_MOTOR_HARDWARE_PUBLIC __attribute__((visibility("default")))
#define DFROBOT_DC_MOTOR_HARDWARE_LOCAL __attribute__((visibility("hidden")))
#else
#define DFROBOT_DC_MOTOR_HARDWARE_PUBLIC
#define DFROBOT_DC_MOTOR_HARDWARE_LOCAL
#endif
#define DFROBOT_DC_MOTOR_HARDWARE_PUBLIC_TYPE
#endif

#endif  // DFROBOT_DC_MOTOR_HARDWARE__VISIBILITY_CONTROL_H_
