<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="diffbot" params="prefix">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="base_mass" value="0.3" /> <!-- arbitrary value for base mass -->
  <xacro:property name="base_width" value="0.14" />
  <xacro:property name="base_length" value="0.14" />
  <xacro:property name="base_height" value="0.05" />
  <xacro:property name="wheel_mass" value="0.3" /> <!-- arbitrary value for wheel mass -->
  <xacro:property name="wheel_len" value="0.020" />
  <xacro:property name="wheel_radius" value="0.0175" />
  <xacro:property name="imu_height" value="0.04" /> <!-- Height of IMU below top plate -->
  

  <!-- Base Link -->
  <link name="${prefix}base_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_width} ${base_length} ${base_height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_width} ${base_length} ${base_height}"/>
      </geometry>
      <material name="acrylic"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${base_mass}"/>
      <inertia
        ixx="${base_mass / 12.0 * (base_length*base_length + base_height*base_height)}" ixy="0.0" ixz="0.0"
        iyy="${base_mass / 12.0 * (base_height*base_height + base_width*base_width)}" iyz="0.0"
        izz="${base_mass / 12.0 * (base_width*base_width + base_length*base_length)}"/>
      </inertial>
    </link>

    <!-- left wheel Joint -->
    <joint name="${prefix}left_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}left_wheel"/>
      <origin xyz="0.02 ${base_width/2} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.2"/>
    </joint>

    <joint name="${prefix}base_footprint_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}base_footprint"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>

    <!-- left wheel Link -->
    <link name="${prefix}left_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
        <material name="red"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="${wheel_mass / 12.0 * (3*wheel_radius + wheel_len*wheel_len)}" ixy="0.0" ixz="0.0"
          iyy="${wheel_mass / 12.0 * wheel_radius*wheel_radius}" iyz="0.0"
          izz="${wheel_mass / 12.0 * wheel_radius*wheel_radius}"/>
        </inertial>
      </link>
    <!-- right wheel Joint -->
    <joint name="${prefix}right_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}right_wheel"/>
      <origin xyz="0.02 -${base_width/2} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.2"/>
    </joint>

    <!-- right wheel Link -->
    <link name="${prefix}right_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
        <material name="red"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="${wheel_mass / 12.0 * (3*wheel_radius + wheel_len*wheel_len)}" ixy="0.0" ixz="0.0"
          iyy="${wheel_mass / 12.0 * wheel_radius*wheel_radius}" iyz="0.0"
          izz="${wheel_mass / 12.0 * wheel_radius*wheel_radius}"/>
        </inertial>
      </link>

          <!-- IMU Sensor -->
    <link name="${prefix}imu_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="0.02 0.02 0.01"/>
        </geometry>
        <material name="red"/>
      </visual>
    </link>

    <joint name="${prefix}imu_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}imu_link"/>
      <origin xyz="-0.02 0.01 ${base_height - imu_height}" rpy="0 0 ${PI}"/>
    </joint>

          <!-- Lidar Sensor -->
    <link name="${prefix}laser">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="0.055 0.055 0.04"/>
        </geometry>
        <material name="black"/>
      </visual>
    </link>

    <joint name="${prefix}laser_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}laser"/>
      <origin xyz="0 0 ${base_height + 0.04}" rpy="0 0 ${PI}"/>
    </joint>


    <!-- Camera -->
    <link name="${prefix}camera_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="0.01 0.025 0.025"/>
        </geometry>
        <material name="green"/>
      </visual>
    </link>

    <joint name="${prefix}camera_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}camera_link"/>
      <origin xyz="0.08 0 ${base_height - imu_height}" rpy="0 0 0"/>
    </joint>

    <link name="${prefix}camera_link_optical"></link>

    <joint name="${prefix}camera_optical_joint" type="fixed">
      <parent link="${prefix}camera_link"/>
      <child link="${prefix}camera_link_optical"/>
      <origin xyz="0 0 0" rpy="${-PI/2} 0 ${-PI/2}"/>
    </joint>

  </xacro:macro>

</robot>
